kind: pipeline
name: default

steps:
    - name: lint
      image: golangci/golangci-lint
      commands:
          - golangci-lint run

    - name: test
      image: golang
      commands:
          - go test -v -coverprofile cover.out ./...
          - go tool cover -func cover.out

    - name: benchmark
      image: golang
      commands:
          - go test -bench=. ./...
